### ISSUE TITLE
matplotlib plots don't work if not in the main thread (autofocus vcurve)

### ISSUE THREAD

**Issue by blumzi** [The-MAST-project/MAST_unit#10]
```
Traceback (most recent call last):
  File "C:\Users\mast\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\mast\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mast\PycharmProjects\MAST_unit\src\plotting.py", line 122, in plot_autofocus_analysis
    plt.show()
  File "C:\Users\mast\PycharmProjects\MAST_unit\venv\Lib\site-packages\matplotlib\pyplot.py", line 612, in show
    return _get_backend_mod().show(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mast\PycharmProjects\MAST_unit\venv\Lib\site-packages\matplotlib\backend_bases.py", line 3540, in show
    manager.show()  # Emits a warning for non-interactive backend.
    ^^^^^^^^^^^^^^
  File "C:\Users\mast\PycharmProjects\MAST_unit\venv\Lib\site-packages\matplotlib\backends\_backend_tk.py", line 556, in show
    self.canvas.manager.window.attributes('-topmost', 1)
  File "C:\Users\mast\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 2051, in wm_attributes
    return self.tk.call(args)
           ^^^^^^^^^^^^^^^^^^
RuntimeError: main thread is not in main loop
```

**Comment by blumzi** [comment]
The plot files (.png) get created but displaying them is tricky since we run in threads underneath uvicorn.
Anyhow noone will look at them in real-time in production

**Comment by blumzi** [comment]
now using matplotlib.use("Agg") as a non-interactive backend for corrections plots
