### ISSUE TITLE
Seems that the filer moves the file away before it is written

### ISSUE THREAD

**Issue by blumzi** [The-MAST-project/MAST_unit#21]
Happened with writing of corrections.json, while it was open for writing.

**Comment by blumzi** [comment]
```
2024-11-03 19:59:35,280 - INFO     - {mast.unit.solving:solve_and_correct:acquisition:12356} -  solve_and_correct:spec: target: [23.000000000, 24.000000000], solved: [22.999998305, 23.999995399], delta: [0.000001548, 0.000004601], tolerance: [0.000005556, 0.000083333]
2024-11-03 19:59:35,284 - INFO     - {mast.unit.solving:solve_and_correct:acquisition:12356} -  solve_and_correct:spec: within tolerances, deltas: (0.083617536, 0.016564197) tolerance: (0.300000000, 0.300000000)
2024-11-03 19:59:35,289 - INFO     - {mast.unit.common.activities:end_activity:acquisition:12356} -  ended activity <UnitActivities.Solving: 256>, duration=0:02:39.741043
Traceback (most recent call last):
  File "C:\Users\mast\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\mast\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mast\PycharmProjects\MAST_unit\src\acquirer.py", line 212, in do_acquire
    self.latest_acquisition.save_corrections(phase)
  File "C:\Users\mast\PycharmProjects\MAST_unit\src\acquisition.py", line 32, in save_corrections
    with open(path, 'w') as fp:
```
